### ISSUE TITLE
smart-m600.cfg - TELEGRAM_FILAMENT_RUNOUT

### ISSUE THREAD

**Issue by schlaubi666** [rootiest/zippy-klipper_config#4]
i try to use telegram plugin ( https://github.com/nlef/moonraker-telegram-bot/wiki  )  + smart-m600 to send a notification whey runout is detected.
the telegram stuff is working but the command TELEGRAM_FILAMENT_RUNOUT 
gives the error

Unknown command:"TELEGRAM_FILAMENT_RUNOUT"

how to setup correctly ?

**Comment by schlaubi666** [comment]
found the telegram.cfg

**Comment by schlaubi666** [comment]
i added the telegram.cfg, but it not wokring whith the pligin i have (  https://github.com/nlef/moonraker-telegram-bot/wiki ). some hints what to change ?

**Comment by rootiest** [comment]
Yeah that's because I use moonraker-telegram ([https://github.com/Raabi91/moonraker-telegram](https://github.com/Raabi91/moonraker-telegram)) You can't just copy that telegram.cfg file unless you use the same extension.

None of that is really relevant to the smart-m600 macro though. All it does is call a macro called `TELEGRAM_FILAMENT_RUNOUT`. You can make a macro with that name to do whatever you want.

You could make something like:

    [gcode_macro TELEGRAM_FILAMENT_RUNOUT]
    gcode:
        RESPOND PREFIX=tgalarm_photo MSG="Filament runout!"

which I believe should work with moonraker-telegram-bot.

In the future I plan to make some of those macro names configurable in the variables at the top of the file.
