### ISSUE TITLE
3.3V source on SKR Pico

### ISSUE THREAD

**Issue by SinDukan** [rootiest/zippy-klipper_config#6]
Hi,

thank you very much for your howto. It is very well written and correct. I just wnated to not, that the SKR Pico actually has a 3.3v source for the CAN Adapter to run from. it is located on the 5-pin SWD header. the middle pin is GND and the outer pin towards the tmc2209s is 3.3V.

https://gadgetangel.org/build/electrical/images/SKR_PICO_V1.0_Color_PIN_diagram.jpg

**Comment by rootiest** [comment]
Ah yeah that is totally fair, and is actually probably a better connection to go with for that reason.

That said, I used the connector I did personally because of convenience, as it's easy to access from the outside if you have any kind of case on your board, and mine at least came with a pre-crimped connector that would work without any soldering.

Also, FWIW (and don't take this as applying to _**everything**_) but I've found that many components labeled for 3.3V will take 5V just fine, and I knew that was the case with the CAN transceiver I used.

I will add a note about this to the guide though, thanks for pointing it out!

**Comment by rootiest** [comment]
Actually, looking more into it, I don't think the SWD pins are addressable, so you would need to use that 3.3V and maybe ground and still use the UART or another set of pins for the canbus data...

**Comment by SinDukan** [comment]
Yes, that is indeed the way I run it, 2 cables go to SWD for power, the other two to gpio 0 and 1, like depicted in your how-to. It works perfectly fine.

**Comment by rootiest** [comment]
I added a note to the guide about alternative pins and their advantages: https://github.com/rootiest/zippy-klipper_config/commit/4c1e5322ce7c816914da3f3ef30928d8bf79c9bf

Thanks for the suggestion! 👍
